#!/usr/bin/env perl


while($ARGV[0]=~/^-/) {
	my $opt=shift;
	last if($opt eq '--');
	
	if($opt=~s/^-p//) { $prefix=1; unshift(@ARGV, '-'.$opt) if($opt ne ""); }

	else { die "$opt: invalid option"; }
}



while(<>) {
	my ($t, $post, $origin, $view, $comm, $star)=split /\s+/;
	
	if(defined $m{$post}) {
		print "$t ";
		#print "$post " if($prefix);
		print $view-$m{$post}," ", $prefix? $post:"", "\n";
	}
	$m{$post}=$view;
}
