#!/usr/bin/env perl
# from_epoch() UT
use DateTime;

my $tz='Europe/Moscow';
while($ARGV[0]=~/^-/) {
	my $opt=shift;
	last if($opt eq '--');
	
	if($opt=~s/^-z//) { $tz=($opt eq "")? shift : $opt; }
	
	else { die "$opt: invalid option"; }
}


foreach(@ARGV) {
	my $t=DateTime->from_epoch('epoch' => $_, 'time_zone' => $tz);
	print "$t\n";
}



