#!/usr/bin/env perl
use LWP::UserAgent;
use HTML::TokeParser;
use DateTime;
use DateTime::TimeZone;
use utf8;

my $path='.';

while($ARGV[0]=~/^-/) {
	my $opt=shift;
	last if($opt eq '--');
	
	if($opt=~s/^-r//) { $raw_page=1; push(@ARGV, '-'.$opt) if($opt ne ""); }
	elsif($opt=~s/^-p//) { $path= ($opt eq "")? shift : $opt; }

	elsif($opt=~s/^-h//) { usage(); exit(0); }
	else { usage(); die "$opt: invalid option"; }
}
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");


my $agent=new LWP::UserAgent;
$agent->agent("habra/1.0");


for(my $n=1; my $page=get_page("http://habrahabr.ru/posts/top/page".$n); $n++) {
	my $stream=HTML::TokeParser->new(\$page) or die "parser: $!";

	while(my $t=to_post($stream)) {
		my $id=$t->[1]->{id};
		my ($post_date,@stat)=post_stat($stream);
		my ($at, $since)=post_date($post_date);

#		print "$id.$at		", $since,"    @stat\n";
		save_stat("$id.$at", $since, @stat);
	}
}




sub get_page
{
	my $req=HTTP::Request->new(GET => shift);
	my $rsp=$agent->request($req);

	return $rsp->decoded_content() if($rsp->is_success);
	undef;
}




sub to_post
{
	my $stream=shift;
	my $t=$stream->get_tag("div");
	while(not $t->[1]->{class}=~/^post\s.*shortcuts_item$/) {
		last if(not $t);
		$t=$stream->get_tag("div");
		last if(not $t);
	}
	return $t;
}





sub post_stat
{
	my $stream=shift;
	my $ident=0;
	my @stat=();
	while(my @t=@{$stream->get_tag("div","/div")}) {
		if($t[0] eq "/div") {
			last if($ident == 0);
			$ident--;
		} elsif($t[0] eq "div") {
			$ident++;
			if($t[1]->{class} eq "pageviews") {
				push @stat, $stream->get_text();
			} elsif($t[1]->{class} eq "favs_count") {
				push @stat, $stream->get_text();
			} elsif($t[1]->{class} eq "comments") {
				my $cnt=$stream->get_text("/span");
				$cnt=~s/^[^0-9]*//; $cnt=0 if($cnt eq "");
				push @stat, $cnt;
			} elsif($t[1]->{class} eq "published") {
				push @stat, $stream->get_text();
			}
		}
	}
	@stat;
}
	

sub post_date
{
	my $post_date=shift;
	my $at=DateTime->now->set_time_zone('Europe/Moscow');
	my $now=DateTime->now->set_time_zone('Europe/Moscow');
	$post_date=~s/(.*) //;

	if($1 eq "вчера в") {
		$at->set_day($now->day-1);
	} elsif($1 eq "сегодня в") {
	} else {
			die "$1 $post_date: bad date format";
	}
	my ($hr, $mn)=split /:/, $post_date;
	$at->set_hour($hr);
	$at->set_minute($mn);
	$at->set_second(0);
	
	($at, $now->epoch-$at->epoch());
}


sub save_stat
{
	my $file=shift;
	local (*FILE);	

	open(FILE, ">> $path/$file") or die "$file: $!";
	print FILE "@_\n";
	close(FILE);
}


sub usage
{
	print "Synopsis: xabra [-p <path>] [-r] [-h]\n";
	print "Options:\n";
	print "  -p <path>    : target path to save stat\n";
	print "  -r           : dump raw page (not impl)\n";
	print "  -h           : print this help and quit\n";
}


sub strdump
{
	foreach(@_) {
		my @l=split //;
		foreach(@l) { print ord($_)," "; }
		print "\n";
	}
}




